// Run against a disposable database: node scripts/smoke-test.mjs [--cloud]
// --cloud creates small test images and deletes only those images via the API.
import assert from 'node:assert/strict'
import { randomBytes } from 'node:crypto'

const base = process.env.SMOKE_API_URL || 'http://127.0.0.1:8123/api'
const cloud = process.argv.includes('--cloud')
const prefix = `smoke_${Date.now()}`
const password = randomBytes(18).toString('base64url')
const resources = []
const clients = [client(), client()]
const users = []

function client() {
  const cookies = new Map()
  return async (path, body, options = {}) => {
    const headers = { Cookie: [...cookies].map(([k, v]) => `${k}=${v}`).join('; ') }
    if (!(body instanceof FormData) && body !== undefined) headers['Content-Type'] = 'application/json; charset=UTF-8'
    const response = await fetch(`${base}${path}`, {
      method: body === undefined ? 'GET' : 'POST', headers,
      body: body === undefined ? undefined : body instanceof FormData ? body : JSON.stringify(body),
      signal: AbortSignal.timeout(45000),
    })
    for (const cookie of response.headers.getSetCookie()) {
      const first = cookie.split(';', 1)[0]
      const pos = first.indexOf('=')
      cookies.set(first.slice(0, pos), first.slice(pos + 1))
    }
    const result = await response.json()
    if (!options.error) assert.equal(result.code, 0, `${path}: ${result.message}`)
    return result
  }
}

async function upload(request, spaceId, id) {
  const form = new FormData()
  // 32x32 RGB PNG generated by Java ImageIO, no remote downloads.
  const bytes = Buffer.from('iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAIAAAD8GO2jAAAANUlEQVR4Xu3NIREAIADAQDpRknCEIgBiBtzfvZrZmGt/Ne70lkEySAbJIBkkg2SQDJJBMkgHk6ccW7Vj9I0AAAAASUVORK5CYII=', 'base64')
  form.set('file', new Blob([bytes], { type: 'image/png' }), `${prefix}.png`)
  if (spaceId) form.set('spaceId', spaceId)
  if (id) form.set('id', id)
  return (await request('/picture/upload', form)).data
}

try {
  assert.equal((await clients[0]('/health')).data, 'ok')
  for (let i = 0; i < clients.length; i++) {
    const userAccount = `${prefix}_${i}`
    await clients[i]('/user/register', { userAccount, userPassword: password, checkPassword: password })
    await clients[i]('/user/login', { userAccount, userPassword: password })
    const user = (await clients[i]('/user/get/login')).data
    assert.equal(user.userAccount, userAccount)
    users.push(user)
  }
  const owner = clients[0], stranger = clients[1]
  const spaceId = (await owner('/space/add', { spaceName: prefix, spaceLevel: 0, spaceType: 0 })).data
  resources.push({ request: owner, type: 'space', id: spaceId })
  await owner('/space/edit', { id: spaceId, spaceName: `${prefix}_edited` })
  assert.equal((await owner(`/space/get/vo?id=${spaceId}`)).data.spaceName, `${prefix}_edited`)
  assert.notEqual((await stranger(`/space/get/vo?id=${spaceId}`, undefined, { error: true })).code, 0)
  const scopedSpaces = (await stranger('/space/list/page/vo', { userId: users[0].id, current: 1, pageSize: 10 })).data
  assert.ok(scopedSpaces.records.every(space => space.userId === users[1].id), 'space listing must enforce owner scope')
  for (const path of ['/picture/list/page/vo', '/picture/list/page/vo/cache']) {
    const denied = await stranger(path, { spaceId, current: 1, pageSize: 10,
      spaceUser: { spaceRole: 'admin' } }, { error: true })
    assert.notEqual(denied.code, 0, `${path} must reject forged admin role`)
  }
  console.log('PASS: registration, login, space create/edit, private list/cache denial')

  const teamId = (await owner('/space/add', { spaceName: `${prefix}_team`, spaceLevel: 0, spaceType: 1 })).data
  resources.push({ request: owner, type: 'space', id: teamId })
  const memberId = (await owner('/spaceUser/add', { spaceId: teamId, userId: users[1].id, spaceRole: 'editor' })).data
  await stranger('/picture/list/page/vo', { spaceId: teamId, current: 1, pageSize: 10 })
  const escalate = await stranger('/spaceUser/edit', { id: memberId, spaceRole: 'admin',
    spaceUser: { spaceRole: 'admin' } }, { error: true })
  assert.notEqual(escalate.code, 0, 'editor cannot promote self')
  console.log('PASS: team editor admission and privilege escalation denial')

  if (cloud) {
    const picture = await upload(owner, spaceId)
    resources.push({ request: owner, type: 'picture', id: picture.id })
    const before = (await owner(`/space/get/vo?id=${spaceId}`)).data
    assert.equal(Number(before.totalCount), 1)
    assert.notEqual((await owner('/space/delete', { id: spaceId }, { error: true })).code, 0,
      'nonempty spaces cannot be deleted')
    const replacement = await upload(owner, spaceId, picture.id)
    assert.equal(replacement.id, picture.id)
    const after = (await owner(`/space/get/vo?id=${spaceId}`)).data
    assert.equal(Number(after.totalCount), 1, 'replacing an image must not increment count')
    assert.equal(Number(after.totalSize), Number(replacement.picSize))
    const denied = await stranger(`/picture/get/vo?id=${picture.id}`, undefined, { error: true })
    assert.notEqual(denied.code, 0)
    assert.notEqual((await owner('/picture/search/picture', { pictureId: picture.id }, { error: true })).code, 0,
      'private images must not be sent to external reverse-image search')
    const imageResponse = await fetch(replacement.url, { signal: AbortSignal.timeout(15000) })
    assert.equal(imageResponse.status, 200, 'authorized signed URL must load')
    await imageResponse.arrayBuffer()
    const unsignedUrl = new URL(replacement.url)
    unsignedUrl.search = ''
    const unsignedResponse = await fetch(unsignedUrl, { signal: AbortSignal.timeout(15000) })
    assert.equal(unsignedResponse.status, 403, 'private COS object must reject anonymous reads')
    await unsignedResponse.arrayBuffer()
    // Override these origins when running against a deployed frontend.
    const corsOrigins = (process.env.SMOKE_CORS_ORIGINS || 'http://localhost:5173,http://127.0.0.1:5173').split(',').map(origin => origin.trim())
    for (const origin of corsOrigins) {
      const corsResponse = await fetch(replacement.url, {
        headers: { Origin: origin }, signal: AbortSignal.timeout(15000),
      })
      assert.equal(corsResponse.status, 200, 'signed cross-origin image must load')
      assert.equal(corsResponse.headers.get('access-control-allow-origin'), origin, 'COS must allow the configured frontend origin')
      await corsResponse.arrayBuffer()
    }
    const deniedCors = await fetch(replacement.url, {
      headers: { Origin: 'https://unapproved.invalid' }, signal: AbortSignal.timeout(15000),
    })
    assert.equal(deniedCors.headers.get('access-control-allow-origin'), null, 'COS must not allow an unapproved origin')
    await deniedCors.arrayBuffer()
    console.log('PASS: private COS rejects unsigned reads; signed reads and approved-origin CORS succeed')
    await Promise.all([upload(owner, spaceId, picture.id), upload(owner, spaceId, picture.id)])
    const current = (await owner(`/picture/get/vo?id=${picture.id}`)).data
    const concurrentUsage = (await owner(`/space/get/vo?id=${spaceId}`)).data
    assert.equal(Number(concurrentUsage.totalCount), 1, 'concurrent replacements must keep a single picture')
    assert.equal(Number(concurrentUsage.totalSize), Number(current.picSize), 'concurrent replacements must match actual size')
    const publicImage = await upload(owner)
    resources.push({ request: owner, type: 'picture', id: publicImage.id })
    assert.notEqual((await client()(`/picture/get/vo?id=${publicImage.id}`, undefined, { error: true })).code, 0,
      'unreviewed public uploads must not be exposed anonymously')
    await owner('/picture/delete', { id: publicImage.id })
    resources.pop()
    console.log('PASS: COS upload/read, serial/concurrent replacement quota, nonempty-space guard, private search/detail denial, public deletion')

    const teamPicture = await upload(owner, teamId)
    resources.push({ request: owner, type: 'picture', id: teamPicture.id })
    const edited = await upload(stranger, teamId, teamPicture.id)
    assert.equal(edited.userId, users[0].id, 'team replacement must preserve original uploader')
    await owner('/spaceUser/delete', { id: memberId })
    const revoked = await stranger('/picture/list/page/vo', { spaceId: teamId, current: 1, pageSize: 10 }, { error: true })
    assert.notEqual(revoked.code, 0, 'removed member loses access')
    console.log('PASS: team replacement ownership and membership revocation')
  }
  // Clean up only objects/rows created in this run, in reverse order.
  while (resources.length) {
    const item = resources[resources.length - 1]
    if (item.type === 'space') {
      const empty = (await item.request(`/space/get/vo?id=${item.id}`)).data
      assert.equal(Number(empty.totalCount), 0, 'deleting all images must release the count')
      assert.equal(Number(empty.totalSize), 0, 'deleting all images must release the size')
    }
    await item.request(`/${item.type}/delete`, { id: item.id })
    resources.pop()
  }
  await clients[0]('/user/logout', {})
  assert.notEqual((await clients[0]('/user/get/login', undefined, { error: true })).code, 0)
  console.log(`PASS: cleanup and logout. Test account prefix: ${prefix}`)
} catch (error) {
  // Print only assertions/messages, never cookies, passwords or signed URLs.
  console.error(`FAIL: ${error.message}`)
  process.exitCode = 1
} finally {
  for (const item of resources.reverse()) {
    try { await item.request(`/${item.type}/delete`, { id: item.id }) }
    catch { console.error(`Cleanup required: ${item.type} id=${item.id}`) }
  }
}
